rc:
  hostname: localhost:8848
  username: nacos
  password: nacos
  namespace: partlocal
ap:
  hostname: 10.100.20.156
  port: 8080
rds:
  idx: 1
  hostname: localhost
  port: 3434
  password: 32423
db:
  master:
    hostname: localhost
    port: 3434
    username: fdsa
    password: dsafds
  slave:
    hostname: localhost
    port: 3434
    username: fdsa
    password: dsafds